<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-6JUGJ4I" failures="2" tests="13" name="TestEdge" time="112.389" errors="0" timestamp="2022-12-21T16:06:42 IST">
  <testcase classname="tests.RegisterPageTest" name="providingBlankPhoneNumber" time="0.83"/>
  <testcase classname="tests.RegisterPageTest" name="providingShortPassword" time="1.007"/>
  <testcase classname="tests.RegisterPageTest" name="providingValidRegistrationData" time="0.968">
    <failure type="java.lang.AssertionError" message="expected [https://accounts.lambdatest.com/email/verify] but found [https://accounts.lambdatest.com/register]">
      <![CDATA[java.lang.AssertionError: expected [https://accounts.lambdatest.com/email/verify] but found [https://accounts.lambdatest.com/register]
at tests.RegisterPageTest.providingValidRegistrationData(RegisterPageTest.java:219)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- providingValidRegistrationData -->
  <testcase classname="tests.RegisterPageTest" name="providingblankEmail" time="2.804"/>
  <testcase classname="tests.RegisterPageTest" name="providingblankUserName" time="3.029"/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldCompnyName" time="0.121">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.RegisterPageTest.testFunctionalFieldCompnyName(RegisterPageTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testFunctionalFieldCompnyName -->
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldDesiredPassword" time="2.053"/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldEmailId" time="2.055"/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldFreeSignUp" time="2.071"/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldFullName" time="2.087"/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldPhoneNumber" time="2.042"/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldTermsAndPrivacyPolicy" time="2.039"/>
  <testcase classname="tests.RegisterPageTest" name="withoutAcceptingTerms" time="1.183"/>
  <testcase classname="tests.RegisterPageTest" name="providingRegisteredEmail" time="0.0">
    <ignored/>
  </testcase> <!-- providingRegisteredEmail -->
</testsuite> <!-- TestEdge -->
